version: '2'

services:
  nginx:
    container_name: skill-up-front
    image: skill-up-app-front
    build: '.'
    ports:
      - 80:80
      - 443:443
    networks:
      - skill-up-app-network

networks:
  skill-up-app-network:
    driver: bridge

